import menu.combo
from menu.combo import regularcombo
from menu.combo import dietcombo
print("Dietcombo test part:")
print("enter coca as drink")
d = dietcombo.Dietcombo(drink = ["coca"])
print("display current combo:")
d.display()
print("check whether drink is diet:")
d.drink_check()
print("add nuggets as snack twice")
d.snack_custom("nuggets")
d.snack_custom("nuggets")
print("add lettuce as snack twice")
d.burger_custom("double meat")
print("check whether calories under standard:")
d.calories_check()
print("display current combo:")
d.display()
print("check whether burger is whether, not reuglar will correct")
d.burger_cal_control()
print("display current combo:")
d.display()
print("calculate total price")
d.total_price()
print("\n")
print("Regularcombo test part:")
r = regularcombo.Regularcombo()
print("add lettuce for burger")
r.burger_custom("lettuce")
print("add chicken finger for snack")
r.snack_custom("chicken finger")
print("add ice for drink")
r.drink_custom("ice")
print("display current combo:")
r.display()
print("calculate total price")
r.total_price()
